# Generated by Django 5.0.4 on 2024-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='platform',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
