# Generated by Django 5.0.4 on 2024-08-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_host_name_alter_room_platform_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host_name',
            field=models.CharField(default='John', max_length=50, null=True),
        ),
    ]
